### ISSUE TITLE
Erreur du plugin Compteur de mots (wordCount)

### ISSUE THREAD

**Issue by geba38490** [franck-paul/wordCount#2]
Bonjour,

La console du navigateur (Chrome) signale une erreur `Uncaught SyntaxError: Unexpected token ':'` . En désactivant les plugins un par un, j'ai trouvé le responsable : Compteur de mots (wordCount).

Merci. Cordialement
Gérard Barré

**Comment by franck-paul** [comment]
Bonjour,

Un peu de contexte serait le bienvenu pour reproduire le problème. C'est côté administration ou public, en faisant quoi …

**Comment by geba38490** [comment]
Bonjour Franck,
Le problème se présente côté administration. Je cherchais pourquoi je constatais un plantage à l'enregistrement d'un billet, voir sur le [forum](https://forum.dotclear.org/viewtopic.php?pid=349780#p349780). La console du navigateur m'a affiché l'erreur. En me connectant à l'administration en mode secours, j'ai constaté que le problème venait des plugins. En mode normal, j'ai désactivé les plugins un par un pour ne plus constater d'erreur. Ainsi le compteur de mots occasionne l'erreur mais pas le plantage à l'enregistrement. Le plugin imgWidthAndHeightAdder provoque l'erreur à l'enregistrement, le problème vient d'être expliqué dans le [ticket](https://codeberg.org/julmud/dc2-imgWidthAndHeightAdder/issues/2).

Cordialement

**Comment by franck-paul** [comment]
Il serait utile d'aller enregistrer (et vérifier) les paramètres du plugin wordCount et refaire le test avec un billet

**Comment by geba38490** [comment]
Je viens de vérifier et de mettre à jour (enregistrer) la configuration du plugin, de nettoyer le cash du navigateur (Chrome). et de relancer l'inspection qui détecte la même erreur quand le plugin est actif. Mais curieusement, je n'ai pas trouvé de difficulté de fonctionnement du plugin, de l'admin, du site (maintenant que la cause du plantage avec imgWidthAndHeightAdder est corrigée dans les billets concernés. 

Cordialement

**Comment by franck-paul** [comment]
La nouvelle version devrait corriger le problème.

**Comment by geba38490** [comment]
Effectivement, la console du navigateur (Chrome) ne détecte plus d'erreur. Super et merci !
