### ISSUE TITLE
Dysfonctionnement du compteur de mots 3.4.2

### ISSUE THREAD

**Issue by geba38490** [franck-paul/wordCount#3]
Bonjour,

Je suis sous Dotclear 2.26.1, PHP 8.2 et le plugin Compteur de mots est à jour (3.4.2). Le contenu des billets rédigés en mode Wiki Dotclear commence toujours par l'insertion d'un code html (Entête et contenu d'un billet au format txt pièce jointe).

Le compteur de mot dans sa version actuelle semble ignorer les mots du contenu, comptabilisant l'entête uniquement. Une précision : si je supprime le code html en tête du contenu, les données du compteur sont bonnes. Les versions précédentes fonctionnaient correctement, sans être perturbées par le code html. J'utilise la balise insérée dans le template adéquat, pas le widget.

Merci. cordialement
Gérard Barré
[sentier-nature-billet-titre-entete-contenu.txt](https://github.com/franck-paul/wordCount/files/12192481/sentier-nature-billet-titre-entete-contenu.txt)

**Comment by geba38490** [comment]
Désolé, je viens de découvrir une erreur dans mon code html:

`<li>[<strong>Franchissement``` <abbr title=Pas de difficultés" `lang="fr">1/3</abbr>`

Il manque un guillemet à l'attribut  title="…"

**Comment by franck-paul** [comment]
Impossible de reproduire le problème.

Avec l'entête seule (plus un X dans le contenu) les compteurs (en cours d'édition) sont :

Compteurs : 679 caractères - 121 mots - ½ folio - moins d'une minute

En rajoutant le contenu les compteurs sont :

Compteurs : 5139 caractères - 885 mots - 3 folios ½ - 4 minutes  
 

Une fois publié, le widget affiche : 5139 caractères - 885 mots - 3 folios ½ - 4 minutes

Et la balise insérée (sans aucune option) affiche : 885 mots

Ce qui semble plutôt cohérent.

**Comment by geba38490** [comment]
Bonjour Franck,
Désolé d'avoir pris de ton temps pour une étourderie dans mon code html, comme je l'expliquais dans mon message précédent et sur le [forum](https://forum.dotclear.org/viewtopic.php?pid=350189#p350189). Je te remercie pour ça.
Je ne souhaite pas mélanger les problèmes, mais j'ai un souci avec la publication des commentaires. La question sur le [forum](https://forum.dotclear.org/viewtopic.php?pid=350192) reste pour l'instant sans réponse.
